steps:
  - name: maven:3.3-jdk-8
    entrypoint: 'mvn'
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=sample/deployment.yml
    - --image=gcr.io/cicd-gke-388407/myapp:latest
    - --location=us-central1
    - --cluster=cluster1
options:
   logging: CLOUD_LOGGING_ONLY

    
