steps:
  - name: maven
    entrypoint: 'mvn'
    args: ['clean', 'package']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA']
options:
   logging: CLOUD_LOGGING_ONLY

    
